---

###
# JAEGER
###

# Version
jaeger_version: latest

###
# DOCKER
###

# Network
jaeger_docker_network:
  name: jaeger
  state: present

# Stack
jaeger_docker:
  env:
    COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
  name: jaeger
  image: jaegertracing/all-in-one:{{ jaeger_version }}
  state: started
  network: jaeger
  ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268
    - 9411:9411
